/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args) {
        Restaurant firstRes = new Restaurant("InDoor");
        firstRes.setStars(3);
        firstRes.setPrice(4);
        firstRes.addReview("Amazing Restaurant" , "Anssam", 5);
        firstRes.addReview("Not Good" , "Anas", 1);
        firstRes.addReview("Not Good" , "Anas", 1);
        firstRes.addReview("Normal" , "Anssam", 2);
//        System.out.println(firstRes.getReview());

        System.out.println(firstRes);
    }
}